spring:
    datasource:
        password: rootpassword
        username: root
    profiles:
        active: prod
        
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
